name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  GO_VERSION: '1.24.2'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Vet
      run: go vet -v ./...

    - name: cilint
      run: go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint run ./...

