on:
  push:
    tags:
      - "v*"

env:
  GO_VERSION: '1.22.0'

name: Release
jobs:
  build:
    name: Release (github.com)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#v}
          go build -o fbmirrors -ldflags="-X main.version=$VERSION" main.go
      - id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            fbmirrors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

