on:
  push:
    tags:
      - "v*"

env:
  GO_VERSION: '1.22.0'

name: Release
jobs:
  build:
    name: Release (github.com)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go build -o fbmirrors main.go
      - id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            fbmirrors
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

